apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-mecanica
  namespace: fiap-mecanica
  labels:
    app: fiap-mecanica
spec:
  selector:
    matchLabels:
      app: fiap-mecanica
  template:
    metadata:
      labels:
        app: fiap-mecanica
    spec:
      containers:
        - name: fiap-mecanica
          image: "423972067332.dkr.ecr.us-east-1.amazonaws.com/fiap-mecanica:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: fiap-mecanica-config
            - secretRef:
                name: fiap-mecanica-secret
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "768Mi"
          startupProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            periodSeconds: 10
